$(function(){
	$("#tabs").tabs();
	$("#tabs-chart").tabs();
	$("#tabs-chart-day").tabs();
	$("#tabs-chart-week").tabs();
	$("#tabs-chart-month").tabs();
	$("#tabs-chart-year").tabs();
	$("#tabs-table").tabs();
	$("#tabs-table-day").tabs();
	$("#tabs-table-week").tabs();
	$("#tabs-table-month").tabs();
	$("#tabs-table-year").tabs();
	});